# Generated by Django 4.1.2 on 2022-11-05 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alliances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('leader', models.CharField(max_length=100)),
                ('motto', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DLC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
            ],
            options={
                'ordering': ['release_date'],
            },
        ),
        migrations.CreateModel(
            name='MonsterSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Zones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('alliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eso_app.alliances')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Trials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dlc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eso_app.dlc')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eso_app.zones')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('clazz', models.ForeignKey(db_column='class', on_delete=django.db.models.deletion.CASCADE, to='eso_app.classes')),
            ],
        ),
        migrations.CreateModel(
            name='Races',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eso_app.alliances')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Mythic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('items', models.CharField(max_length=200)),
                ('dlc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eso_app.dlc')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Dungeons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dlc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eso_app.dlc')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eso_app.zones')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('alliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eso_app.alliances')),
                ('clazz', models.ForeignKey(db_column='class', on_delete=django.db.models.deletion.CASCADE, to='eso_app.classes')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eso_app.races')),
            ],
        ),
        migrations.CreateModel(
            name='Arenas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eso_app.zones')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
