# Generated by Django 4.1.2 on 2022-11-11 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eso_app', '0002_rename_character_characters_rename_dlc_dlcs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zones',
            name='alliance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eso_app.alliances'),
        ),
    ]
