# Generated by Django 4.1.2 on 2022-11-11 20:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eso_app', '0003_alter_zones_alliance'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildEditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=1000)),
                ('alliance', models.CharField(choices=[('ALDMERI', 'Aldmeri Dominion'), ('DAGGERFALL', 'Daggerfall Covenant'), ('EBONHEART', 'Ebonheart Pact')], max_length=50)),
                ('race', models.CharField(choices=[('BRETON', 'Breton'), ('KHAJIT', 'Khajit'), ('ORC', 'Orc'), ('HIGH_ELF', 'High Elf'), ('DARK_ELF', 'Dark Elf'), ('WOOD_ELF', 'Wood Elf'), ('ARGONIAN', 'Argonian'), ('REDGUARD', 'Redguard'), ('NORD', 'Nord'), ('IMPERIAL', 'Imperial')], max_length=30)),
                ('clazz', models.CharField(choices=[('DK', 'Dragonknight'), ('TP', 'Templar'), ('WD', 'Warden'), ('SC', 'Sorcerer'), ('NC', 'Necromancer'), ('NB', 'Nightblade')], db_column='class', max_length=30)),
                ('role', models.CharField(choices=[('T', 'Tank'), ('D', 'Damage Dealer'), ('H', 'Healer')], max_length=50)),
                ('playstyle', models.CharField(choices=[('PVP', 'PVP'), ('PVE', 'PVE')], max_length=10)),
                ('curse', models.CharField(choices=[('V', 'Vampire'), ('W', 'Werewolf')], max_length=50, null=True)),
                ('mundus', models.CharField(choices=[('APPRENTICE', 'The Apprentice'), ('ATRONACH', 'The Atronach'), ('LADY', 'The Lady'), ('LORD', 'The Lord'), ('LOVER', 'The Lover'), ('MAGE', 'The Mage'), ('RITUAL', 'The Ritual')], max_length=100)),
                ('attributes_health', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(64), django.core.validators.MinValueValidator(0)])),
                ('attributes_magicka', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(64), django.core.validators.MinValueValidator(0)])),
                ('attributes_stamina', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(64), django.core.validators.MinValueValidator(0)])),
                ('house', models.CharField(max_length=500)),
                ('mount', models.CharField(max_length=500)),
            ],
        ),
    ]
