# Generated by Django 4.1.2 on 2022-11-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eso_app', '0004_buildeditor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildeditor',
            name='clazz',
            field=models.CharField(choices=[('DK', 'Dragonknight'), ('TP', 'Templar'), ('WD', 'Warden'), ('SC', 'Sorcerer'), ('NC', 'Necromancer'), ('NB', 'Nightblade')], db_column='class', max_length=30, verbose_name='class'),
        ),
    ]
