# Generated by Django 4.1.2 on 2022-11-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eso_app', '0005_alter_buildeditor_clazz'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildeditor',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images/% Y/% m/% d/'),
        ),
    ]
