# Generated by Django 4.1.3 on 2022-11-11 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eso_app', '0006_buildeditor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildeditor',
            name='desc',
            field=models.CharField(max_length=1000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='buildeditor',
            name='playstyle',
            field=models.CharField(choices=[('PVP', 'PVP'), ('PVE', 'PVE')], max_length=10, verbose_name='Play Style'),
        ),
        migrations.AlterField(
            model_name='characters',
            name='clazz',
            field=models.ForeignKey(db_column='class', on_delete=django.db.models.deletion.CASCADE, to='eso_app.classes', verbose_name='class'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='clazz',
            field=models.ForeignKey(db_column='class', on_delete=django.db.models.deletion.CASCADE, to='eso_app.classes', verbose_name='class'),
        ),
    ]
