# Generated by Django 4.1.3 on 2022-11-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eso_app', '0008_alter_buildeditor_attributes_health_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildeditor',
            name='mundus',
            field=models.CharField(choices=[('APPRENTICE', 'The Apprentice'), ('ATRONACH', 'The Atronach'), ('LADY', 'The Lady'), ('LORD', 'The Lord'), ('LOVER', 'The Lover'), ('MAGE', 'The Mage'), ('RITUAL', 'The Ritual'), ('SERPENT', 'The Serpent'), ('SHADOW', 'The Shadow'), ('STEED', 'The Steed'), ('THIEF', 'The Thief'), ('TOWER', 'The Tower'), ('WARRIOR', 'The Warrior')], max_length=100),
        ),
    ]
