# Generated by Django 4.1.3 on 2022-11-11 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eso_app', '0010_buildeditor_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildeditor',
            name='curse',
            field=models.CharField(blank=True, choices=[('V', 'Vampire'), ('W', 'Werewolf')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='buildeditor',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='buildeditor',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='images/% Y/% m/% d/'),
        ),
    ]
