# Generated by Django 4.1.3 on 2022-11-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eso_app', '0011_alter_buildeditor_curse_alter_buildeditor_desc_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buildeditor',
            options={'ordering': ['-name']},
        ),
        migrations.AlterField(
            model_name='buildeditor',
            name='desc',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='Description'),
        ),
    ]
