# Generated by Django 4.1.3 on 2022-11-12 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eso_app', '0012_alter_buildeditor_options_alter_buildeditor_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='races',
            name='alliance',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='eso_app.alliances'),
        ),
        migrations.AlterField(
            model_name='zones',
            name='alliance',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='eso_app.alliances'),
        ),
    ]
