# Generated by Django 4.1.3 on 2022-11-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eso_app', '0014_alter_races_alliance'),
    ]

    operations = [
        migrations.AddField(
            model_name='alliances',
            name='desc',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='arenas',
            name='desc',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='classes',
            name='desc',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='dlcs',
            name='desc',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='dungeons',
            name='desc',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='monstersets',
            name='desc',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='races',
            name='desc',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='roles',
            name='desc',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='skills',
            name='desc',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='trials',
            name='desc',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='zones',
            name='desc',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Description'),
        ),
    ]
