# Generated by Django 4.1.3 on 2022-11-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eso_app', '0015_alliances_desc_arenas_desc_classes_desc_dlcs_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alliances',
            name='image_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='arenas',
            name='image_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='classes',
            name='image_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='dlcs',
            name='image_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='dungeons',
            name='image_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='monstersets',
            name='image_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='mythics',
            name='image_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='races',
            name='image_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='roles',
            name='image_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='skills',
            name='image_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='trials',
            name='image_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='zones',
            name='image_url',
            field=models.URLField(default=''),
        ),
    ]
