# Generated by Django 4.1.3 on 2022-11-12 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eso_app', '0016_alliances_image_url_arenas_image_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skills',
            options={'ordering': ['clazz']},
        ),
    ]
