# Generated by Django 4.1.3 on 2022-11-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eso_app', '0017_alter_skills_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildeditor',
            name='curse',
            field=models.CharField(blank=True, choices=[('V', 'Vampire'), ('W', 'Werewolf')], default='', help_text='Optional', max_length=50),
        ),
    ]
