# Generated by Django 4.1.3 on 2022-11-13 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eso_app', '0018_alter_buildeditor_curse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('HEAD', 'Head'), ('SHOULDERS', 'Shoulders'), ('CHEST', 'Chest'), ('HANDS', 'Hands'), ('BELT', 'Belt'), ('SHOES', 'Shoes'), ('PANTS', 'Pants'), ('NECKLACE', 'Necklace'), ('RING1', 'Ring 1'), ('RING2', 'Ring 2'), ('W1', 'Frontbar Weapon'), ('W2', 'Backbar Weapon')], default='', max_length=500)),
                ('set', models.TextField(default='', max_length=500)),
                ('weight', models.CharField(choices=[('L', 'Light'), ('M', 'Medium'), ('H', 'Heavy')], default='', max_length=100)),
                ('trait', models.CharField(default='', max_length=100)),
                ('enchantment', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='buildeditor',
            name='head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eso_app.gear'),
        ),
    ]
