# Generated by Django 4.1.3 on 2022-11-13 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eso_app', '0019_gear_buildeditor_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildeditor',
            name='backbar_skill_five',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='eso_app.skills'),
        ),
        migrations.AddField(
            model_name='buildeditor',
            name='backbar_skill_four',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='eso_app.skills'),
        ),
        migrations.AddField(
            model_name='buildeditor',
            name='backbar_skill_one',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='eso_app.skills'),
        ),
        migrations.AddField(
            model_name='buildeditor',
            name='backbar_skill_three',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='eso_app.skills'),
        ),
        migrations.AddField(
            model_name='buildeditor',
            name='backbar_skill_two',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='eso_app.skills'),
        ),
        migrations.AddField(
            model_name='buildeditor',
            name='backbar_ultimate',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='eso_app.skills'),
        ),
        migrations.AddField(
            model_name='buildeditor',
            name='backbar_weapon',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='buildeditor',
            name='chest',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='buildeditor',
            name='feet',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='buildeditor',
            name='frontbar_skill_five',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='eso_app.skills'),
        ),
        migrations.AddField(
            model_name='buildeditor',
            name='frontbar_skill_four',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='eso_app.skills'),
        ),
        migrations.AddField(
            model_name='buildeditor',
            name='frontbar_skill_one',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='eso_app.skills'),
        ),
        migrations.AddField(
            model_name='buildeditor',
            name='frontbar_skill_three',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='eso_app.skills'),
        ),
        migrations.AddField(
            model_name='buildeditor',
            name='frontbar_skill_two',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='eso_app.skills'),
        ),
        migrations.AddField(
            model_name='buildeditor',
            name='frontbar_ultimate',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='eso_app.skills'),
        ),
        migrations.AddField(
            model_name='buildeditor',
            name='frontbar_weapon',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='buildeditor',
            name='hands',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='buildeditor',
            name='legs',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='buildeditor',
            name='necklace',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='buildeditor',
            name='ring_one',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='buildeditor',
            name='ring_two',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='buildeditor',
            name='shoulders',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='buildeditor',
            name='waist',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='buildeditor',
            name='head',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
