# Generated by Django 4.1.3 on 2022-11-13 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eso_app', '0020_buildeditor_backbar_skill_five_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildeditor',
            name='video',
            field=models.URLField(blank=True, default=''),
        ),
    ]
