# Generated by Django 4.1.3 on 2022-11-15 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eso_app', '0021_buildeditor_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='clazz',
            field=models.ForeignKey(blank=True, db_column='class', null=True, on_delete=django.db.models.deletion.CASCADE, to='eso_app.classes', verbose_name='class'),
        ),
    ]
