# Generated by Django 4.1.3 on 2022-11-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eso_app', '0024_alter_weapon_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='name',
            field=models.CharField(blank=True, choices=[('Bow', 'Bow'), ('DW', 'Dual Wield'), ('TH', 'Two Handed'), ('SB', 'Sword and Shield'), ('R', 'Restoration'), ('D', 'Destruction')], max_length=200),
        ),
    ]
