# Generated by Django 4.1.3 on 2022-11-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eso_app', '0025_alter_weapon_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
