# Generated by Django 4.1.3 on 2022-11-15 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eso_app', '0026_alter_weapon_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildeditor',
            name='backbar_skill_five',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='eso_app.skills'),
        ),
        migrations.AlterField(
            model_name='buildeditor',
            name='backbar_skill_four',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='eso_app.skills'),
        ),
        migrations.AlterField(
            model_name='buildeditor',
            name='backbar_skill_one',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='eso_app.skills'),
        ),
        migrations.AlterField(
            model_name='buildeditor',
            name='backbar_skill_three',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='eso_app.skills'),
        ),
        migrations.AlterField(
            model_name='buildeditor',
            name='backbar_skill_two',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='eso_app.skills'),
        ),
        migrations.AlterField(
            model_name='buildeditor',
            name='backbar_ultimate',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='eso_app.skills'),
        ),
        migrations.AlterField(
            model_name='buildeditor',
            name='frontbar_skill_five',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='eso_app.skills'),
        ),
        migrations.AlterField(
            model_name='buildeditor',
            name='frontbar_skill_four',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='eso_app.skills'),
        ),
        migrations.AlterField(
            model_name='buildeditor',
            name='frontbar_skill_one',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='eso_app.skills'),
        ),
        migrations.AlterField(
            model_name='buildeditor',
            name='frontbar_skill_three',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='eso_app.skills'),
        ),
        migrations.AlterField(
            model_name='buildeditor',
            name='frontbar_skill_two',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='eso_app.skills'),
        ),
        migrations.AlterField(
            model_name='buildeditor',
            name='frontbar_ultimate',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='eso_app.skills'),
        ),
    ]
